services:

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - APP_DB_CONNECTION_STRING=root:toor@tcp(db:3306)/task_orm?charset=utf8mb4&parseTime=True&loc=Local
      - APP_PORT=8080

  db:
    image: bitnami/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=gromizk123
      - MYSQL_DATABASE=task_orm
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-pgromizk123", "-e", "show schemas"]
      interval: 10s 
